from random import random as random

birthday = 21111990

# Random seed is a variable used to initialize random variables.
# In python numbers generated in "random" aren't truly random, but they are based on a sequence generated by the value
# you pass into the random seed. The most common way to create different numbers/ sets of numbers each time is to leave
# the random.seed() like this, which means that the seed value is the current time (which is different each and every
# moment).
# Passing the same seed to random, and then calling it again and again, will give you the same set of numbers.
# If you want a different -more random- set of numbers, initialize seed with a different value each time.

random.seed(birthday)

for i in range(0, 200):
    xx = random.randint(0, 100)
    yy = random.randint(0, 100)
    table = (xx, yy)
print(table)
